<a href="https://colab.research.google.com/github/zanzivyr/Optimizers/blob/main/GramSchmidt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Gram-Schmidt Orthagonalization

Part of Schur Decomposition is performing Gram-Schmidt Orthogonalization.

This is an essential part of Linear Algebra, so writing this code in python will be very useful in the future.

# Resources

- Dan Gries - https://youtu.be/KOkuTXrv5Gg
- Wikipedia - https://en.wikipedia.org/wiki/Gram%E2%80%93Schmidt_process

In [83]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from numpy import linalg as LA

# Instantiate

Create test vectors to be orthogonalized!

In [84]:
size = 3
vectors = 3

vset = tf.random.uniform(shape=[vectors,size], maxval=10, dtype=tf.float32)
vset.numpy()

array([[1.4213991, 8.486845 , 0.8668721],
       [8.5801525, 6.0056663, 1.4359641],
       [0.5509186, 7.0621085, 2.6476264]], dtype=float32)

# Process

Perform the Gram-Schmidt process to create a orthogonal basis.

In [85]:
basis = vset[0]

for v in range(1, vectors):
  vec = vset[v]

  sum = 0
  for u in range(1, v+1):
    uvec = vset[u]
    sum += np.dot((np.dot(uvec, vec) / np.dot(uvec, uvec)), uvec)

  b = vec - sum
  basis = tf.concat([basis, b], 0)

basis = tf.reshape(basis, (vectors,size), name=None)
basis

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 1.4213991,  8.486845 ,  0.8668721],
       [ 0.       ,  0.       ,  0.       ],
       [-3.9113188, -2.737722 , -0.6545937]], dtype=float32)>

## Normalize

Divide each vector by its L2 norm to create an orthonormal basis set.

In [86]:
ortho = 0

if LA.norm(basis[0]) != 0:
  ortho = tf.math.multiply(basis[0], 1/LA.norm(basis[0]))
else:
  ortho = tf.zeros(size, dtype=tf.float32)

for v in range(1, vectors):
  if LA.norm(basis[v]) != 0:
    o = tf.math.multiply(basis[v], 1/LA.norm(basis[v]))
  else:
    o = tf.zeros(size, dtype=tf.float32)
    
  ortho = tf.concat([ortho, o], 0)

ortho = tf.reshape(ortho, (vectors,size), name=None)
ortho

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.1643501 ,  0.9812964 ,  0.10023259],
       [ 0.        ,  0.        ,  0.        ],
       [-0.81165814, -0.56811893, -0.13583815]], dtype=float32)>